teamsempo/SempoBlockchain

app/server/api/auth_api.py
app/server/models/user.py
test/functional/app/api/test_auth_api.py

Fixing that annoying bug where the otp test failed some time. What was happing was the otp was being forced into an int (don't ask why), so otps such as '012345' were being converted into '12345' which was causing the test to fail 1 in 10 times.

OTP Bug Fix

---

app/server/models/credit_transfer.py
app/server/models/exchange.py

Based on slack discussion regarding transfer types not being set for exchanges. Will also probably include a deeper investigation into transfer subtypes

Transfer Type Improvments

---

app/client/components/pages/transferAccountListPage.jsx
app/client/components/transferAccount/singleTransferAccountWrapper.jsx
app/client/components/transferAccount/transferAccountList.jsx
app/client/reducers/transferAccountReducer.js
app/client/sagas/transferAccountSagas.js
app/server/api/transfer_account_api.py
app/server/models/utils.py

The current Transfer Account List page takes WAAAAAYYYY too long to load (up to a minute when there's 1000s of accounts). Long term fix is server side search etc.
Short term fix :
- Speeding up subsequent load times after the initial by only loading modified accounts 
- Technical improvements to the react rendering process namely:
-      reducing number of re-renderings
-     don't include ALL element a dict used for working out which rows were selected, but rather just assume non-present elements are not selected.

Transfer Account List Performance Fixes

---

app/server/utils/user.py
config.py

Transfer cards were not being assigned correctly when user details were updated, because they weren't being bound to an associated transfer account.

Transfer Card Assignment Fix

---

.gitignore
README.md
app/migrations/seed.py
config_files/public/local_config.ini
contract_setup_script.py
ganache_cli.sh
quick_setup_script.sh

Fixes the issue with the python setup script and creates new more comprehensive bash one:
`quick_setup_script.sh`
To use:
- set env variable `MASTER_WALLET_PK` to the master private key found in your local ini secrets file 
-run `quick_setup_script.sh [activation path for your python env] `
- once that's finished run, start app and worker as normal. Ganache will already be running

More comprehensive setup script

---

app/_docker_app_script.sh
awsDockerrunTemplate.json
docker-compose.yml

uWSGI docs recommend using the [stats server/uwsgitop ](https://uwsgi-docs.readthedocs.io/en/latest/StatsServer.html) to monitor apps and understand performance issues. See also https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html
This PR adds this.

Adding UWSGI Stats Server

---

app/client/sagas/messageSaga.js
app/package.json

Closes #237 
Caused by delay function error when redux was updated
```
Error: call: argument fn is undefined or null
at check (io-6de156f3.js?86aa:33)
at validateFnDescriptor (io-6de156f3.js?86aa:455)
at call (io-6de156f3.js?86aa:524)
at showFlashMessage$ (messageSaga.js?6e97:13)
at tryCatch (runtime.js?f3a2:65)
at Generator.invoke [as _invoke] (runtime.js?f3a2:303)
at Generator.prototype.<computed> [as next] (runtime.js?f3a2:117)
at next (redux-saga-core.esm.js?42a9:1157)
at currCb (redux-saga-core.esm.js?42a9:1251)
at eval (redux-saga-core.esm.js?42a9:481)
eval @ index.js?69b4:3680
index.js?69b4:3680 The above error occurred in task onAddFlashMessage
created by onAddFlashMessage
created by takeEvery(ADD_FLASH_MESSAGE, onAddFlashMessage)
created by rootSaga
created by rootSaga
created by …
```

hot fix for #237

---

app/server/models/credit_transfer.py
config.py

We don't want a transaction to be resolved more than once, this is intended to prevent that from happening

Only resolve transfer as rejected or completed once

---

app/client/components/pages/dashboardPage.jsx
config.py

Currently when you load the dashboard, the system tries to load all transfer accounts, which slows the system down real bad. This load doesn't actually seem to do anything, so this PR removes it.
**Todo**

Remove Transfer Account Load From Dashboard

---

app/client/__fixtures__/creditTransfer/creditTransferData.ts
app/client/__tests__/functional/reducers/creditTransfer/reducers.test.ts
app/client/components/creditTransfer/creditTransferList.jsx
app/client/components/creditTransfer/userCell.jsx
app/client/components/dashboard/userFunnelChart.jsx
app/client/components/management/newTransferManager.jsx
app/client/components/pages/creditTransferListPage.jsx
app/client/components/pages/dashboardPage.jsx
app/client/components/transferAccount/transferAccountManager.jsx
app/client/reducers/creditTransfer/actions.ts
app/client/reducers/creditTransfer/reducers.ts
app/client/reducers/creditTransfer/types.ts
app/client/reducers/rootReducer.ts
app/client/reducers/transferAccount/types.ts
app/client/sagas/creditTransferSagas.js
app/client/sagas/creditTransferSagas.ts
app/client/sagas/transferAccountSagas.js
app/client/sagas/transferAccountSagas.ts

converts the `creditTransfer` reducer to typescript following the format of the `messages` reducer, and adds a couple specs
**Q:**
~~I saw references to `PUSHER_*` actions that look unused ... are those deprecated now?~~

convert CreditTransfer reducer to typescript and add a couple tests

---

README.md
config.py
eth_worker/_docker_worker_script.sh
eth_worker/requirements.txt
worker/Dockerfile
worker/_beat_starter.sh

Eventlet is causing failures in our CI pipeline, that Gevent doesn't seem to cause. In lieu of having a strong opinion about using greenthreads or not, swapping to the more popular library that doesn't break seems like the wise move!
**Todo**

Swapping Eventlet for Gevent in eth workers

---

app/client/sagas/authSagas.ts
app/package-lock.json
app/package.json

After logging into the dashboard, it's possible to have a race condition where the session token is accessed by another call before it's stored, which logs the system out. 
The make the session token storage synchronous, preventing said condition
**Todo**
- ~~[ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request~~

Remove Dashboard Auth Race Condition

---

app/server/api/transfer_card_api.py
app/test_app/functional/test_transfer_card_api.py
config.py

A short modification to the transfer card get request that ensures that only cards that are actually bound to users are returned. Will be replaced by a full sharding solution shortly.
Also includs tests for the transfer card api
**Todo**

Only get bound transfer cards

---

app/migrations/seed.py
config.py

Currently, when the update_date migration is run on instance boot, specified transfer usages are liable overwritten by the default usages provided in the seed script. This PR prevents the default usages from being added unless no transfer usages  currently exist.
**Todo**

Don't overwrite transfer usages during dataset upgrade if usages already exist

---

app/server/utils/attribute_preprocessor.py
config.py

Option in data pre-processor to set whether wrapped data overwrites wrap data or vice-versa
**Todo**

Configurable option on data wrapper

---

config.py
eth_worker/eth_src/sql_persistence/interface.py
eth_worker/test_eth_worker/unit/test_third_party_sync.py

We were doing stupidly many UPDATEs  for each `SynchronizedBlock`, and that was using an alarming amount of database capacity. This does one big, clean batch-UPDATE. 
**Todo**

Make SynchronizedBlock be updated in batch instead of one giant update

---

config.py
eth_worker/eth_src/sql_persistence/interface.py

Whenever we update `BlockchainTransaction`, the `/api/v1/blockchain_taskable` webhook is called. The problem is that we update `BlockchainTransaction` when we don't have to a lot of the time (like when the state changes from `PENDING` to `PENDING`), leading to a bunch of webhook calls that don't ever really have to happen. This tests to make sure that we _need_ to update, before we actually do!     
**Todo**

Only update BlockchainTransaction on the worker when we absolutely have to

---

app/client/components/dashboard/MetricsCard.jsx
app/package.json

Loading spinner was throwing a bunch of warnings in the console. This just casts to the input to the type it wants silence it.
**Todo**

Silence loading spinner warning

---

app/server/api/transfer_usage_api.py
app/server/models/organisation.py
app/server/utils/amazon_s3.py
app/server/utils/auth.py
app/server/utils/metrics/filters.py
app/server/utils/ussd/token_processor.py
app/test_app/unit/utils/ussd/kenya/test_pin_state.py
config.py
eth_worker/eth_src/celery_app.py
eth_worker/eth_src/eth_manager/contract_registry/contract_registry.py

Been playing with [vulture](https://pypi.org/project/vulture/), and thought I should do a super quick PR to get rid of some unused imports. 
**Todo**

Remove unused imports

---

app/server/api/metrics_api.py
app/server/utils/metrics/metrics_cache.py
app/test_app/functional/api/test_metrics_api.py
config.py

Sometimes if we change the past, the cache gets invalidated and we get some strange behaviour. This adds an endpoint to nuke the cache for a given org if we have to
**Todo**

Add endpoint to flush metrics cache

---

app/client/components/navBar/OrgSwitcher.tsx
app/client/components/organisation/OrganisationForm.tsx
app/client/components/pages/settings/OrganisationPage.tsx
app/client/components/pages/settings/settingsPage.jsx
app/client/nav.jsx
app/package.json
postman/SempoBlockchain.postman_collection.json

Renames `Organisation` to `Project` on the frontend. Lightweight refactor of only the frontend names exposed to user. Component Names, redux state, backend API etc. are still called organisations. This causes some issues with the API errors returning "Organisation" but it's limited. I don't think a further refactor is worth it unless it's the whole codebase (which would be a breaking change v2.0.0). 
**Todo**

refactor: rename organisation to project

---

app/requirements.txt
app/test_app/functional/api/test_metrics_api.py
test_requirements.txt

Freezes time at dummy-data creation time to make sure the tests don't blow up at any time of the day  
**Todo**

Stabilize metrics tests

---

app/client/components/intercom/IntercomSetup.tsx
app/package.json

User's with the same `userId` and `companyId` (i.e. multiple instances) will see the same chat. This risks sharing sensitive information between customers when interacting with customer support. This implements a fix by making the id's more unique with the concatenation of additional attributes.
NOTE: all existing users will lose their previous support chat history
**Todo**

fix: intercom unique id bug

---

app/client/components/creditTransfer/singleCreditTransfer.jsx
app/package.json

Fixes the credit transfer page crashing when accessed from an individual transfer account. For some reason, the state is slightly different from that page and includes a object as a value, which isn't supported.
**Todo**

fix: credit transfer page crash

---

CHANGELOG.md
app/server/utils/metrics/metric.py
config.py

Ensures date filter doesn't apply to master wallet metrics.  
**Todo**

Ensure date filter doesn't apply to master wallet metrics

---

app/server/models/transfer_account.py
app/test_app/unit/models/test_transfer_account.py
config.py

Transactions in the `PARTIAL` state were not being counted properly, and as such the balances were incorrect when running a bulk disbursement. This rectifies that error, and adds additional testing.
**Todo**

Fix partial-state transaction balance bug

---

app/client/sagas/transferAccountSagas.ts

This PR fixes a bug introduced in #726 that caused `credit_sends` to be overridden by `credit_recieves` in the transferAccountSaga when loading an individual transfer account with credit transfers (i.e. `/accounts/1/` page). Caused by this line change: https://github.com/teamsempo/SempoBlockchain/pull/726/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.py&file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx#r664225919
**Todo**

fix: creditTransfer reducer overwrite bug

---

app/server/api/disbursement_api.py
config.py

Metrics cache should be cleared after bulk action, since cache being written to while a disbursement is taking place can lead to double-counting
**Todo**

Clear cache after bulk action

---

app/client/components/history/historyDrawer.tsx
app/package.json

If there was a null from the history API, the history drawer would crash. This makes it a bit more robust!   
**Todo**

Make history drawer work with incomplete data
