teamsempo/SempoBlockchain

app/server/__init__.py, app/server/api/kyc_application_api.py, app/server/models.py, app/server/schemas.py, app/server/utils/auth.py, app/server/utils/feedback.py, app/server/utils/namescan.py, app/server/utils/slack_controller.py
Merging verification and other mobile changes into the real multi-tenant branch
Bad branch naming on my part 😬
=> Multi tenant demo

app/migrations/seed.py, app/server/utils/ussd/kenya_ussd_processor.py, app/server/utils/ussd/ussd.py, test/unit/app/utils/test_ussd.py
- seed for menus
- add in more test cases since preferred_language fixed
=> ussd menu migrations

app/client/api/transferUsagesAPI.js, app/client/components/transferAccount/transferAccountList.jsx, app/client/components/user/CreateUser.tsx, app/client/components/user/CreateUserForm.tsx, app/client/reducers/organisation/reducers.ts, app/client/reducers/organisation/types.ts, app/client/reducers/rootReducer.ts, app/client/reducers/transferUsage/actions.ts, app/client/reducers/transferUsage/reducers.ts, app/client/reducers/transferUsage/types.ts, app/client/sagas/organisationSagas.js, app/client/sagas/rootSaga.js, app/client/sagas/transferUsageSagas.js, app/client/schemas.js, app/server/models/transfer_usage.py, app/server/utils/user.py
- fix accounts not showing up on accounts page
- reducers and saga for business categories
- also reducers for organisations, not used yet
- hook in reducer to user form
- other selection
=> hook in business category to admin user creation

app/server/api/user_api.py, app/server/models/custom_attribute_user_storage.py, app/server/models/organisation.py, app/server/models/user.py, app/server/utils/i18n.py, app/server/utils/user.py, app/server/utils/ussd/directory_listing_processor.py, app/server/utils/ussd/kenya_ussd_state_machine.py, app/server/utils/ussd/ussd_tasks.py, test/unit/app/models/test_organisation.py, test/unit/app/utils/ussd/test_directory_listing.py
directory listing fully functional and tested. code isn't great and it's no longer on a background thread...
screenshot of there not being any users matching and then there being users matching:
=> implement directory listing

app/client/api/authApi.js, app/client/api/businessVerificationAPI.js, app/client/api/creditTransferAPI.js, app/client/api/exportAPI.js, app/client/api/filterAPI.js, app/client/api/qrCodeApi.js, app/client/api/spreadsheetAPI.js, app/client/api/transferAccountAPI.js, app/client/api/transferUsagesAPI.js, app/client/api/userAPI.js, app/client/api/wyreAPI.js, app/client/app.jsx, app/client/components/auth/registerForm.jsx, app/client/components/pages/singleUserPage.jsx, app/client/components/pages/transferAccountListPage.jsx, app/client/components/user/singleUserManagement.jsx, app/client/reducers/rootReducer.ts, app/client/sagas/authSagas.js, app/client/utils.js, app/server/api/auth_api.py, app/server/utils/credit_transfer.py
- bug fixes
- auto login invited users once password (and if required TFA token) are set
=> Multi orgs bug fixes

app/client/api/userAPI.js, app/client/components/user/singleUserManagement.jsx, app/server/api/user_api.py, app/server/locale/general_sms.en.yml, app/server/locale/general_sms.sw.yml, app/server/utils/user.py, test/functional/app/api/test_user_api.py, test/unit/app/utils/test_utils_user.py
=> adding pin reset sms

app/client/components/creditTransfer/creditTransferList.jsx, app/client/components/navBar.jsx, app/client/components/transferAccount/transferAccountManager.jsx, app/client/components/user/singleUserManagement.jsx, app/server/templates/index.html, config.py, test/functional/app/views/test_index.py
The old system could only point to etherscan. Now we can point to xdai on the blockexplorer via config settings
=> Adding configurable blockexplorer links

app/client/components/user/singleUserManagement.jsx, app/server/api/user_api.py, app/server/models/user.py, app/server/utils/user.py, test/functional/app/api/test_user_api.py
* change user type (admin or super admin)
* edit user tests
=> change user type

config.py
Via @EDsCODE
> updated config.py with nick so that config.py uses local environment variables (DATABASE_USER, DATABASE_PASSWORD) when starting postgres
=> Remerge: Local Dev Settings

app/server/models/utils.py, app/server/utils/misc.py, app/server/utils/user.py, app/server/utils/ussd/kenya_ussd_state_machine.py, app/server/utils/ussd/token_processor.py, test/functional/app/api/test_ussd_api.py, test/unit/app/utils/ussd/kenya/test_exchange_state.py
- rounding exchange rates amounts on sms's to 3 sig figs
- not requesting pin for exchange rate
- devious bug resulting in random pending transactions that stop transfer limits from working
=> GE Bug Fixes

app/server/locale/ussd.en.yml, app/server/locale/ussd.sw.yml, test/functional/app/api/test_ussd_api.py, test/unit/app/utils/ussd/test_token_processor.py
Just some yaml wording changes
=> Wording changes

.circleci/config.yml, config.py
=> fixing pip on deploy

app/server/utils/ge_migrations/rds_migrate.py, config.py
both the lines deleted and the CreditTransfer init were adding the balance during migration, which resulted in users recording double balance, so this fixes it!
=> Double Balance in Migration

app/server/wsgi.py, config.py
Yo dawgggg.
Heard you like fixes for your proxy fixes....
Werkzeug dep just got bumped to 1.0.0, and broke an old import
=> Fixing the proxy fix

app/server/locale/ussd.sw.yml
=> Swahili marketplace fix

app/client/components/dashboard/metricsBar.jsx, app/server/utils/credit_transfer.py, config.py
Hopefully fixes the bad numbers in the dashboard
=> Dashboard chart fix

app/client/components/dashboard/metricsBar.jsx, app/client/components/dashboard/userFunnelChart.jsx, app/package.json, app/server/utils/credit_transfer.py, config.py
-removes the inaccurate user filter applied to total users/beneficiary metrics
-implements ui labels that denote which fields have a filter applied
=> Dashboard filter ui update

app/server/locale/ussd.en.yml, app/server/locale/ussd.sw.yml, config.py, test/unit/app/utils/ussd/test_token_processor.py
- exchange limit SMS updated to reflect GE request
- removed newlines on several messages
=> Update copy of exchange_limit_request sms 

app/server/api/user_api.py, config.py
Fixing an issue where cards scanned don't return a balance
=> Get Card Balance Fix

app/server/locale/ussd.en.yml, app/server/locale/ussd.sw.yml, app/server/utils/user.py, app/server/utils/ussd/token_processor.py, config.py
Adding error messages when users hit transfer amount limits
Accidently branched off transfer_card fix, so ignore the first commit
=> Transfer amount limit message

app/server/locale/general_sms.en.yml, app/server/locale/general_sms.sw.yml, config.py, test/unit/app/utils/test_utils_user.py
adding Safaricom and Airtel service codes
=> pin reset message update

.sempoconfig/_SOPS_load.py, .sempoconfig/docker_test_secrets.ini, .sempoconfig/local_secrets.ini, .sempoconfig/meta.ini, .sempoconfig/test_secrets.ini, config.py, config_files/generate_dev_test_secrets.py
Last PR doesn't work on AWS, this PR fixes it
=> Config refactor fixing

.circleci/config.yml
Original Dev build got AWS'd. Now pointing to new build
=> Swapping AWS build env to dev2

.circleci/config.yml
=> swapping aws build env to dev3

app/package-lock.json, app/server/templates/index.html, app/server/views/index.py, config_files/public/local_config.ini
Routes are now all handled on client-side. The server now returns default index.html file. Also removed loading spinner from index.html as could be confusing if it fails for some reason
=> simpler route handling

app/client/components/management/newTransferManager.jsx
Little bug in transfer manager, was getting errors doing bulk disbursements
=> Fix newTransferManager

app/client/sagas/authSagas.js, app/package.json
=> fix tfa error

pgbouncer/generate_pgbouncer_config.py
pgbouncer config bucket was hardcoded. this fixes.
=> Pgbouncer config fix

app/client/components/creditTransfer/creditTransferList.jsx, app/client/components/dashboard/beneficiaryLiveFeed.jsx, app/client/components/transferAccount/transferAccountList.jsx, app/client/components/user/userList.jsx, app/package-lock.json, app/package.json
* Cursor pointer for clickable rows (user & transfer account)
* Removing null name display from `CreditTransferList` and `LiveFeed`
* Null row bug fix
=> Style fixes

app/Dockerfile, config.py
Curl was removed in PR #231 breaking CodeCov upload. Adding it back in.
=> Fix: Adding back curl

.circleci/config.yml, app/package.json
Fixing circle CI jest tests memory issue. See https://discuss.circleci.com/t/memory-problems-with-jest-and-workers/10297
**Todo**
=> fix(ci): frontend tests memory

config.py, test/conftest.py
Pusher not patched in `mock_pusher`
=> fix(test): pusher not patched in mock_pusher

app/client/__tests__/setup/setupTests.js, app/client/__tests__/unit/api/apiClient.test.js, app/client/__tests__/utils.test.js, app/client/api/apiClient.js, app/client/api/pusherAPI.js, app/client/utils.js, app/package-lock.json, app/package.json
Adding unit tests for apiClient and setting up jest api mocking for Saga testing
**Todo**
- ~~[ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request~~
=> test: adding unit tests for apiClient and setting up jest api mocking

app/client/components/navBar/index.tsx, app/package.json
User would be immediately kicked out upon logging in due to a small bug in #265. This fixes that!
Edit: meant #265, not 275 :doge:
**Todo**
=> hotfix: Fix user login

app/client/__tests__/unit/api/apiClient.test.js, app/client/api/authAPI.js, app/client/api/authAPI.ts, app/client/api/businessVerificationAPI.js, app/client/api/client/apiClient.ts, app/client/api/client/types.ts, app/client/api/creditTransferAPI.js, app/client/api/exportAPI.js, app/client/api/exportAPI.ts, app/client/api/filterAPI.js, app/client/api/filterAPI.ts, app/client/api/organisationApi.js, app/client/api/organisationApi.ts, app/client/api/spreadsheetAPI.js, app/client/api/transferAccountAPI.js, app/client/api/transferUsagesAPI.js, app/client/api/transferUsagesAPI.ts, app/client/api/userAPI.ts, app/client/api/wyreAPI.js, app/package-lock.json, app/package.json, config_files/public/local_config.ini
Converting API client to typescript. Only converting the relevant API files that also have Typescript Reducers/Sagas.
**Todo**
- ~~[ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request~~
=> refactor: typescriptify API client

config.py, eth_worker/eth_manager/processor.py
I accidentally deleted our eth worker "update to success" without meaning to! This puts it back in, and actually improves the location since theres now no chance of race conditions
**Todo**
=> Fix: Task update on worker

app/test_app/functional/api/test_search_api.py, config.py
Some tests weren't running because they were missing the test_ prefix.
=> Add test_ to name of test

app/client/components/user/CreateUserForm.tsx, config.py
Commenting out unused signup form fields. We should implement a column on the Organisation field to define active signup fields.
**Todo**
=> fix: commenting out unused signup form fields

app/server/__init__.py, config.py, eth_worker/eth_src/celery_app.py
Adds domain to tags 
Sample issue: https://sentry.io/organizations/sempo/issues/1815447683/?project=1228844&referrer=slack  
**Todo**
=> Attach domain to sentry tags

.circleci/config.yml, devtools/quick_setup_script.sh, eth_worker/_docker_worker_script.sh, eth_worker/requirements.txt
Moving back to eventlet with a pin on dnspython version because gevent had some side effects
**Todo**
=> Move away from gevent again

config.py, eth_worker/requirements.txt
We previously had dnspython  as pinned requirement to it breaking dependency on eventlet. Eventlet has patched themselves on the latest version so this is just upgrading to this version to keep things clean
**Todo**
=> Upgrading eventlet

app/server/api/auth_api.py, app/server/utils/misc.py, config.py
Fixing login flow on mobile to deal with some conflicts between incremental login and the multiorg delegator
**Todo**
=> Login tweaks

app/server/utils/phone.py, app/test_app/functional/api/test_user_api.py, config.py
SMS was breaking when phones werent defined (for example with trnasfer cards)
**Todo**
=> Phone number error fix

app/client/components/koboCredentials.tsx, app/package-lock.json, app/package.json
External auth password was being set as username on frontend.
**Todo**
=> Kobo frontend fix

app/server/api/organisation_api.py, config.py
Trailing slash in add user to org api endpoint, for consistency
=> One slash less

app/client/components/navBar/index.tsx, app/package.json
Sometimes custom logos wouldn't load. I have a hunch that this is why!  
**Todo**
=> Fix custom logo issue

config.py, postman/SempoBlockchain.postman_collection.json
Adds mock data API to postman.
**Todo**
- ~~[ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request~~
=> Mock data postman

app/client/components/adminUser/adminUserList.jsx, app/client/components/form/InputField.tsx, app/client/components/form/MultipleChoice.tsx, app/client/components/form/WrappedInput.tsx, app/client/components/organisation/OrganisationSettingsForm.tsx, app/client/components/pages/InvitePage.jsx, app/client/components/pages/dashboardPage.jsx, app/client/components/pages/settings/OrganisationPage.tsx, app/client/components/transferAccount/transferAccountList.jsx, app/client/components/transferAccount/transferAccountManager.jsx, app/client/components/user/CreateUser.tsx, app/client/components/user/CreateUserForm.tsx, app/client/components/user/EditUserForm.tsx, app/client/components/user/SingleUserManagement.tsx, app/client/components/user/userList.jsx, app/package.json, app/server/api/transfer_account_api.py, app/server/constants.py, app/server/models/organisation.py, app/server/utils/transfer_filter.py, config.py
A clear and concise description of the features implemented in the PR of bugs fixed.
**Todo**
=> Half working hiding

app/client/components/dashboard/beneficiaryLiveFeed.jsx, app/package-lock.json, app/package.json
Fixes a few small naming issues on live feed:
- "Reclamation" being classified as a "withdrawal"
- Adds the admin user email for disbursements and reclamations
- Changes `sent` to `paid`
**Todo**
=> Naming issues

app/server/api/auth_api.py, app/test_app/functional/api/test_auth_api.py, config.py
An admin should not be able to invite a superadmin.
**Todo**
=> Fix critical invite admin error

.circleci/config.yml, app/client/components/QRShowingModal.tsx, app/client/components/koboCredentials.tsx, app/package-lock.json, app/package.json, app/server/api/transfer_card_api.py, config.py
Making it easier to log into the Sempo card sync app using a QR code, rather than needing to type in a long password into a tiny mobile phone screen
**Todo**
=> Adding quick login functionality for card sync

app/server/utils/auth.py, config.py
Tiny tweak to allow a long list of transfer usages on the android app.
**Todo**
=> Removing Transfer Usage Limit

app/client/sagas/authSagas.ts, app/package-lock.json, app/package.json
`index.tsx` in the navBar directory was loading before organisation data was populated. This is due to `LoginAction.loginSuccess` being called _before_ the organisation data has been updated in the redux state. This caused an issue, as the logo URL is called _only once_ in `componentDidMount`, this meant that the `activeOrganisation` props was `undefined`, causing the logo to not load.
Another solution would be to move the URL code from componentDidMount to render, but this would cause the URL to be requested multiple times.
**Todo**
=> Fix logo lifecycle issue

app/server/api/auth_api.py, app/test_app/functional/api/test_auth_api.py, config.py
This makes emails case insensitive  
**Todo**
=> Make emails case insensitive

app/client/components/filterModule/SearchBoxWithFilter.jsx, app/package-lock.json, app/package.json
The new filter module wasn't working on the user list page - small PR to get it working before we upgrade it properly
**Todo**
=> Filter Fix

app/client/components/AsyncButton.jsx, app/client/components/adminUser/InviteForm.jsx, app/client/components/auth/TFAForm.jsx, app/client/components/auth/TFAValidator.jsx, app/client/components/auth/loginForm.jsx, app/client/components/auth/registerForm.jsx, app/client/components/auth/requestResetEmailForm.jsx, app/client/components/auth/resetPasswordForm.jsx, app/client/components/creditTransfer/creditTransferList.jsx, app/client/components/funding/wyreBankFunding.jsx, app/client/components/management/exportManager.jsx, app/client/components/management/newTransferManager.jsx, app/client/components/messageBar.tsx, app/client/components/organisation/OrganisationSettingsForm.tsx, app/client/components/pages/businessVerificationPage.jsx, app/client/components/pages/uploadPage.jsx, app/client/components/transferAccount/transferAccountManager.jsx, app/client/components/uploader/uploadButton.jsx, app/client/components/user/CreateUserForm.tsx, app/client/components/user/EditUserForm.tsx, app/client/components/verification/businessBankDetails.jsx, app/client/components/verification/businessBankDocuments.jsx, app/client/components/verification/businessBankLocation.jsx, app/client/components/verification/businessDetails.jsx, app/client/components/verification/businessDocuments.jsx, app/package-lock.json, app/package.json
There are known bugs caused by using Google Translate Chrome extension that causes a react app to crash. This resolves app crashing on new disbursement and user account pages when using Google Translate by aggressively adding `<span></span>` around all buttonText components.
See:
- https://github.com/facebook/react/issues/11538#issuecomment-390386520
- https://guoyunhe.me/en/2019/06/02/fix-react-issues-with-google-translate/
**Todo**
=> Fix google translate crashing app

app/server/api/vendor_payout_api.py, config.py
Adding a phone number to CSV export
**Todo**
=> Csv phone number

app/test_app/functional/api/test_vendor_payout.py, config.py
Fixes the CSV export api by adding phone number
**Todo**
=> Csv phone test

app/server/api/vendor_payout_api.py, config.py
Vendor payout API had unhandled exceptions that were causing 500 server errors. this handles.
**Todo**
=> Adding error messages to vendor payout

app/client/components/dashboard/card/VolumeChart.jsx, app/package.json
Zero-pads dates up to today when there are no date filters are active  
**Todo**
=> Zero-pad dates til today

app/client/components/dashboard/card/VolumeChart.jsx, app/package.json
Data was modified in-place when it shouldn't have been. This fixes!  
**Todo**
=> Fix transfer graph currency bug

app/server/api/export_api.py, config.py
Adding phone to xlsx export
**Todo**
=> export phone in xlsx

.circleci/config.yml, app/server/models/user.py
Emergency removal of last seen to see if it improves db perf
**Todo**
=> Removing Last Seen

app/client/components/dashboard/card/GroupByChart.jsx, app/client/components/dashboard/card/VolumeChart.jsx, app/client/utils.js, app/package.json
- improves `utils.js` to not return symbol when undefined or null
- improves groupby and volume chart to show formatted currency on axises and tooltips
**Todo**
=> Improved chart formatting

app/client/components/pages/authPage.jsx, app/package.json
=> fixing login link

.circleci/config.yml, config.py, eth_worker/eth_src/eth_manager/eth_transaction_processor.py
When a hash isn't found, the eth worker crashes - fixes!
**Todo**
=> Adding catch for hash not found

app/requirements.txt, app/server/__init__.py, config.py, eth_worker/requirements.txt
Sentry has sqlalchemy and redis extensions. This gives breadcrumbs when reporting on redis or sqlalchemy errors. Very helpful!
**Todo**
=> Update sentry, add integrations

.circleci/config.yml, app/server/constants.py, config.py
Account types was missing from the list of default attributes, so this gets it!
**Todo**
=> Custom attr list fix

app/client/components/dashboard/card/GroupByChart.jsx, app/client/components/dashboard/card/VolumeChart.jsx, app/client/components/theme.js, app/package.json
Adding more informative labels to the legend and adding new more colours
**Todo**
=> Chart Tweaks

app/client/components/dashboard/card/VolumeChart.jsx, app/package.json
Label was playing up - fixes
**Todo**
=> Another Legend Tweak

config.py, eth_worker/eth_src/eth_manager/transaction_supervisor.py
**Describe the Pull Request**  
We were trying `check_transaction_response` way too much, too fast. This fixes!    
**Todo**
=> Stop retrying infinitely

.circleci/config.yml, app/server/api/credit_transfer_api.py, app/test_app/functional/api/test_credit_transfer_api.py, config.py
**Describe the Pull Request**  
If an external user who transacted with one of our existing users transacts with a stranger, we don't want to track that!
**Todo**
=> Improve external transaction detection

app/server/models/user.py, config.py
JWT library returns bytes locally, but a string on circle. I couldn't find exactly where, but a dependency somewhere down the line must have changed at some point. This makes both versions work!
**Todo**
=> Circle was being weird. This fixes it!

app/server/api/export_api.py, config.py
Custom Attributes were not being exported properly - due to the swap to names being stored on a different table, looking up `atttribute.name` was failing
**Todo**
=> Fix to make sure custom attributes are included on export

app/test_app/functional/api/test_dataset_api.py, config.py
Running the tests was leaving behind `spreadsheet.xlsx`. This nukes that!
**Todo**
=> Delete dummy spreadsheet a test was adding

config.py, devtools/build_docker.sh
Runs `npm install` before building in docker build script
**Todo**
=> Update docker build script

app/server/api/search_api.py, config.py
Search wasn't mapping permissions to schemas, now it is!  
**Todo**
=> Add sub-admin schema to search

app/client/components/management/newTransferManager.jsx, app/package.json, app/server/api/credit_transfer_api.py, app/server/utils/credit_transfer.py, config.py
Adds the ability for a balance transfer to be zero. Useful for bulk setting all users on the platform to zero at end of the program.
**Todo**
=> fix: enable zero balance

app/server/api/auth_api.py, app/server/templates/invite_existing_user_email.txt, app/server/utils/amazon_ses.py, app/test_app/functional/api/test_auth_api.py, config.py
When an existing user is invited they will now be added to the new organisation. Also adds a lot more tests for the permission API. Closes #305 
**Todo**
=> fix: link existing user to org on invite

eth_worker/requirements.txt
Tested, doesn't break anything!  
**Todo**
=> Update crypto package

app/server/api/organisation_api.py, config.py
Sempoadmins are too cool and didn't want to be associated with the organisations they create. This fixes that.
**Todo**
=> fix: new org association via sempoadmin tier

app/test_app/functional/api/test_user_api.py, config.py
1/10 times, the tests will fail. This fixes!  
**Todo**
=> Fix one in ten test failure

app/client/components/uploader/uploadedTable.jsx, app/client/reducers/spreadsheet/types.ts, app/package.json, app/server/api/dataset_api.py, config.py
Adds support for custom attributes to XLS upload.  Formerly only bio and gender worked, since they are hard-coded special cases. Now they work, and any other custom attribute works too! 
**Todo**
=> Add custom attributes to xls upload

app/server/api/auth_api.py, config.py
Adds backcompatability to the auth api so that old android versions can still log in
**Todo**
=> Adding Pin Backcompatability

app/client/components/navBar/OrgSwitcher.tsx, app/client/components/navBar/index.tsx, app/client/components/navBar/page.tsx, app/package.json
Hide Intercom chat if ID is null.
**Todo**
=> refactor: hide intercom chat if ID is null

app/client/components/auth/registerForm.jsx, app/client/components/auth/resetPasswordForm.jsx, app/package.json
SOC 2 recommends 8 characters or above for the minimum password.
**Todo**
=> refactor: increase min suggested password length to 8 characters

app/client/components/organisation/OrganisationForm.tsx, app/client/components/pages/settings/OrganisationPage.tsx, app/package.json, app/server/api/organisation_api.py, config.py
Add lat/lng to project settings. Change organisation response message.
**Todo**
=> refactor: organisation lat/lng

SECURITY.md
Adding responsible disclosure policy as recommended by SOC 2.
**Todo**
- ~~[ ] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.~~
- ~~[ ] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver~~
=> refactor: add responsible disclosure policy

app/client/components/externalAuthCredentials.tsx, app/package.json
Also checks the boxes by default   
**Todo**
=> Rename return raw on error

CHANGELOG.md, config.py, eth_worker/eth_src/celery_app.py, eth_worker/eth_src/eth_manager/blockchain_sync/blockchain_sync.py, eth_worker/test_eth_worker/conftest.py, eth_worker/test_eth_worker/unit/test_third_party_sync.py
`createFilter` has proven unreliable, so this switches to the much better `getLogs`!
**Todo**
=> Fix transaction sync

app/client/api/creditTransferAPI.ts, app/client/components/creditTransfer/creditTransferList.jsx, app/client/components/creditTransfer/singleCreditTransfer.jsx, app/client/components/pages/creditTransferListPage.jsx, app/client/components/pages/singleCreditTransferPage.jsx, app/client/nav.jsx, app/client/reducers/creditTransfer/types.ts, app/package.json, app/server/api/credit_transfer_api.py, app/server/schemas.py
Adds a simple transfer details page. Thought about adding things like a timeline and a map - then realized this should just be as simple as possible!!!
**Todo**
=> feat: transfer details page

app/client/components/transferAccount/StandardTransferAccountList.tsx, app/package.json
Adds default value to disbursement form  
**Todo**
=> Adds default value to disbursement form

app/client/components/transferAccount/TransferAccountList.tsx, app/package.json
Add total records to pagination.
**Todo**
=> add total records

app/client/components/transferAccount/StandardTransferAccountList.tsx, app/package.json
This relabels the disbursement button!  
**Todo**
=> Relabel disbursement button

app/client/components/pages/singleBulkDisbursementPage.jsx, app/package.json
Bulk disbursement page was super slow! This paginates the bulk disbursement page  
**Todo**
=> Paginate bulk disbursement page

app/client/components/adminUser/InviteForm.jsx, app/client/components/pages/InvitePage.jsx, app/client/nav.jsx, app/client/sagas/authSagas.ts, app/package.json
Refactor to ant design. Adds tooltips. Adds link to docs.withsempo.com.
**Todo**
- ~~[ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)~~
=> refactor: invite page

app/client/components/pages/singleBulkDisbursementPage.jsx, app/package.json, app/server/api/token_api.py
Disable disbursement approve/reject buttons when disbursement is rejected  
**Todo**
=> Disable disbursement approve/reject buttons when disbursement is rejected

app/client/components/organisation/OrganisationForm.tsx, app/client/components/pages/settings/OrganisationPage.tsx, app/client/reducers/organisation/types.ts, app/client/reducers/user/types.ts, app/migrations/versions/e365daf2570f_.py, app/server/api/disbursement_api.py, app/server/api/organisation_api.py, app/server/models/credit_transfer.py, app/server/models/disbursement.py, app/server/models/organisation.py, app/server/schemas.py, config.py, config_files/public/local_config.ini, config_files/templates/specifc_config_template.ini
Moves multi-approve to config file  
**Todo**
=> Move multi-approval to config file

app/client/components/pages/singleBulkDisbursementPage.jsx, app/package.json, app/server/api/disbursement_api.py, app/server/models/disbursement.py, app/server/schemas.py, config.py
Add links to approvers 
**Todo**
=> Add approvers links

app/server/utils/metrics/filters.py, app/server/utils/metrics/transfer_stats.py, config.py
Filter out incomplete transfers from metrics  
**Todo**
=> Filter out incomplete transfers from metrics

app/server/models/credit_transfer.py, app/server/models/disbursement.py, config.py
A sempoadmin can instantly approve a transfer now!  
**Todo**
=> Sempoadmin overrides multi-approval config

app/server/models/credit_transfer.py, config.py
Some transfers were stuck in 'UNSTARTED' when they should have been 'PENDING'. This fixes!  
**Todo**
=> Fix unstarted blockchain status

app/client/components/dashboard/card/GroupByChart.jsx, app/client/components/dashboard/card/VolumeChart.jsx, app/package.json
Increase font size of chart labels by 20%.
**Todo**
=> fix: fontSize of chart labels

.circleci/config.yml, app/server/__init__.py, config.py, proxy/default.conf
A clear and concise description of the features implemented in the PR of bugs fixed.
**Todo**
=> Hide nginx version header

app/client/components/dashboard/card/GroupByChart.jsx, app/client/components/dashboard/card/VolumeChart.jsx, app/package.json
Small changes to improve chart readability. Improves y and x axes label spacing.
**Todo**
=> fix: chart readability

app/client/components/dashboard/MasterWalletCard.jsx, app/client/components/dashboard/MasterWalletManagementModal.jsx, app/client/components/navBar/OrgSwitcher.tsx, app/client/components/navBar/WalletListModal.tsx, app/client/nav.jsx, app/client/reducers/auth/types.ts, app/client/reducers/organisation/types.ts, app/client/sagas/authSagas.ts, app/package.json, app/server/schemas.py, config.py
Adds an overview of organisation balances and quick links to wallet management.
**Todo**
=> feat: improve master wallet management

app/client/components/transferAccount/TransferAccountList.tsx, app/package.json
A change in #704 broke the bulk disbursements page. This makes it so the page still loads (though the select logic still needs fixing)
**Todo**
=> Make bulk disbursements page not crash

app/client/components/pages/singleBulkDisbursementPage.jsx, app/client/components/transferAccount/StandardTransferAccountList.tsx, app/client/components/transferAccount/TransferAccountList.tsx
The fix to the disbursement page crashed the transfer accounts page. This fixes that
**Todo**
=> Fix to transfer accounts page

app/client/components/pages/notFoundPage.jsx, app/client/nav.jsx, app/package.json
Refactor 404 page to ant design.
**Todo**
=> refactor: 404 page

app/client/components/adminUser/adminUserList.jsx, app/client/sagas/authSagas.ts, app/package.json
Refactor admin list to ant design.
**Todo**
=> refactor: admin list

app/client/components/user/SingleUserManagement.tsx, app/package.json
Fixes phone number bug
**Todo**
=> fix: phone number bug

.circleci/config.yml, app/server/api/disbursement_api.py, app/server/api/metrics_api.py, app/server/models/credit_transfer.py, app/server/utils/metrics/metrics_cache.py, app/test_app/functional/api/test_metrics_api.py
A clear and concise description of the features implemented in the PR of bugs fixed.
**Todo**
=> Rebuild metrics cache after flush

config.py, docker-compose.yml
Docker's postgres image was broken, so we have to set it to a fixed version so it works.   
**Todo**
=> Fix issue psql is having in passing circle tests

app/server/api/credit_transfer_api.py, app/server/models/credit_transfer.py, config.py
When new transactions were being found on the blockchain, the transaction-checker was warning us that they weren't checked yet. Actually they CAME FROM the checker! Now the checker will know better than to stumble into that blunder.
**Todo**
=> Fix small transaction sync bug

app/package-lock.json, app/package.json
Was getting errors on commit because of a deprecated prettier dependency. This fixes!
**Todo**
=> Add prettier dependency

app/server/api/auth_api.py, app/server/api/user_api.py, app/server/models/user.py, config.py
Let superadmins reset password!  
**Todo**
=> Reset password for superadmins

.circleci/config.yml, app/server/__init__.py, app/webpack.config.js
Most of the work for this is in AWS, but we need a few things here:  
- Webpack doesn't need to make gzipped files anymore, cloudfront does that for us  
- We don't have to redirect anymore, cloudfront does that for us too  
- We have to upload the updated static assets to a dev bucket on deploy 
**Todo**
=> Do things needed for static on S3

app/client/components/transferAccount/transferAccountManager.jsx, app/client/components/user/EditUserForm.tsx, app/package.json
A clear and concise description of the features implemented in the PR of bugs fixed.
**Todo**
=> Add confirm screen for form submissions

.circleci/config.yml, app/requirements.txt
Build was broken due to dependency changes. This fixes that!.
**Todo**
=> Fix requirements

app/client/components/dashboard/MasterWalletCard.jsx, app/package.json
Adds tooltips to master wallet metrics  
**Todo**
=> Add tooltips

app/migrations/seed.py, app/server/models/transfer_account.py, config.py
We hit [this](https://app.slack.com/client/T8KAS8287/C019J68NXR7/thread/C019J68NXR7-1651198090.957559) error because our float account doesn't have an org. This fixes currently, and for future deploys!  
**Todo**
=> Fix seed script, and create fallback for existing deploys

app/client/components/transferAccount/export/exportModal.jsx, app/client/reducers/export/types.ts, app/package.json, app/server/api/export_api.py, config.py
Export now works with "selected" when exporting transfers! It's also much faster  
**Todo**
=> Make export honor selected

app/client/components/creditTransfer/singleCreditTransfer.jsx, app/server/schemas.py
=> Add transfer card serial number to API and FE

app/server/models/ip_address.py, app/server/utils/auth.py, config.py
This refreshes IP addresses "updated" column every time a user connects from a given IP address. This lets us more accurately infer the last time they used the platform!  
**Todo**
=> Refresh ip address updated to see user activity time

app/server/api/dataset_api.py
https://sentry.io/organizations/sempo/issues/3265056121/?project=1228844&referrer=slack  
**Todo**
=> Fixes missing "percent complete" variable on user bulk import

README.md, devtools/install_python_requirements.sh
Tiny fix to docs and reqs script  
**Todo**
=> Update requirements scripts, and their documentation

app/client/components/creditTransfer/singleCreditTransfer.jsx, app/server/schemas.py
Adds transfer usages to transfer page  
**Todo**
=> Add transfer usages to transfer page

app/server/api/vendor_payout_api.py, config.py
If we're going to relist a withdrawal, we should make sure they really are withdrawals!   
**Todo**
=> Only add old withdrawals to payout csvs

app/client/components/transferAccount/StandardTransferAccountList.tsx, app/package.json
Bulk disbursement POST data was URL encoded. This URL-Decodes it!  
**Todo**
=> Fix filter when creating bulk disbursement 

app/client/components/creditTransfer/singleCreditTransfer.jsx, app/package.json, app/server/models/credit_transfer.py, app/server/schemas.py, config.py, config_files/public/local_config.ini
Adds resolution messages to credit transfer page  
**Todo**
=> Add resolution messages to credit transfer page

app/client/components/transferAccount/StandardTransferAccountList.tsx, app/package.json
PR #817 broke the admin filtering ability.
**Todo**
=> fix: admin filter functionality

app/client/components/auth/registerForm.jsx, app/package.json
Update minimum password length to 8 characters in `registerForm.jsx` `PasswordInput` component to meet SOC 2 Type 2 requirements.
**Todo**
=> Min password length

app/server/api/vendor_payout_api.py, app/server/locale/general_sms.en.yml, app/server/locale/general_sms.sw.yml, app/server/utils/phone.py, app/server/utils/slack_controller.py, app/server/utils/trulioo.py, app/server/utils/user.py, app/server/utils/ussd/directory_listing_processor.py, app/server/utils/ussd/ussd_state_machine.py, app/test_app/functional/api/test_ussd_api.py, config.py
Add i18n to all SMS messages, and move over to a function that translates automagically
**Todo**
=> Add i18n to all SMS

app/server/api/disbursement_api.py, app/server/models/credit_transfer.py, app/server/utils/credit_transfer.py, app/test_app/functional/api/metrics_outputs/all_by_account_type.json, app/test_app/functional/api/metrics_outputs/all_by_account_type_filtered_by_recipient.json, app/test_app/functional/api/metrics_outputs/all_by_account_type_filtered_by_sender.json, app/test_app/functional/api/metrics_outputs/all_by_coordinates.json, app/test_app/functional/api/metrics_outputs/all_by_location_halifax.json, app/test_app/functional/api/metrics_outputs/all_by_recipient_colour.json, app/test_app/functional/api/metrics_outputs/all_by_recipient_location.json, app/test_app/functional/api/metrics_outputs/all_by_sender_colour.json, app/test_app/functional/api/metrics_outputs/all_by_sender_location.json, app/test_app/functional/api/metrics_outputs/all_filtered_by_recipient_chip_type.json, app/test_app/functional/api/metrics_outputs/all_filtered_by_sender_chip_type.json, app/test_app/functional/api/metrics_outputs/all_filtered_by_sender_chip_type_and_colour.json, app/test_app/functional/api/metrics_outputs/all_ungrouped.json, app/test_app/functional/api/metrics_outputs/all_ungrouped_halifax.json, app/test_app/functional/api/metrics_outputs/credit_transfer_by_transfer_type.json, app/test_app/functional/api/metrics_outputs/credit_transfer_by_transfer_usage.json, app/test_app/functional/api/metrics_outputs/requested_metric_active_users.json, app/test_app/functional/api/metrics_outputs/user_by_account_type.json, app/test_app/functional/api/test_bulk_disbursement_api.py, app/test_app/functional/api/test_credit_transfer_api.py, app/test_app/functional/api/test_master_wallet_api.py, app/test_app/functional/api/test_metrics_api.py, app/test_app/functional/api/test_transfer_account_api.py, app/test_app/functional/api/test_user_api.py, app/test_app/unit/utils/test_utils_user.py, config.py
On bulk disbursements, or single transfers, this checks that you can actually afford it!    
**Todo**
=> Make it harder to spend org cash which doesn't exist

.circleci/config.yml, config.py
Removes ugx and vut from deploy scripts  
**Todo**
=> Remove ugx and vut

app/server/models/credit_transfer.py
Sometimes the card wasn't updated when it should have been. This fixes! 
**Todo**
=> Update transfer card more often

config.py
I forgot to bump the version in my last few PRs, and I want to create a release. This bumps the version so I can create a uniquely named release.
=> Bump Version

app/server/me_api/credit_transfer.py
Allow negative balances with card transfers. Cards are single source of truth, so if they're overloaded, trust the card and examine later.   
**Todo**
=> Allow negative balances with card transfers

app/client/components/transferAccount/transferAccountManager.jsx, app/package.json, app/server/models/transfer_account.py, app/server/models/transfer_card.py, app/server/models/transfer_card_usage.py, app/server/schemas.py, config.py
Adds last_known_card_balance to FE and API  
**Todo**
=> Add last_known_card_balance to FE and API

app/server/api/vendor_payout_api.py, config.py
Silly mistake in last rounding PR. This fixes!  
**Todo**
=> Fix rounding issue

.circleci/config.yml, app/server/__init__.py, app/server/api/disbursement_api.py, app/server/models/disbursement.py, app/server/sempo_types.py, app/server/utils/executor.py, app/server/utils/location.py, app/server/utils/metrics/metrics.py, app/test_app/conftest.py, app/test_app/functional/api/test_bulk_disbursement_api.py, config.py
Gets rid of flask-executor in all places, except for one occasion where we use it to calculate multiple metrics at once before the values are returned.  
Also adds some pretty major performance increases to the bulk disbursement flow. Subtle changes in terms of LoC, but major w.r.t performance (especially perceived performance to the end-user)
**Todo**
=> Deprecates our use of flask-executor (for the most part)

app/client/components/creditTransfer/singleCreditTransfer.jsx, app/package.json, app/server/schemas.py, app/test_app/functional/api/test_credit_transfer_api.py, config.py
Shows who approved a transfer on the frontend!  
**Todo**
=> Show who approved transfer

.circleci/config.yml, app/server/utils/executor.py, config.py
Tiny fix to get transactions in the right session
=> Patch executor when pusher used

app/server/api/disbursement_api.py, config.py
=> Paginate disbursement API

app/client/components/pages/singleBulkDisbursementPage.jsx, app/server/api/disbursement_api.py, app/server/api/vendor_payout_api.py
Makes a bulk disbursement object for each vendor payout  
**Todo**
=> Visualize vendor payouts as bulk disbursements

app/client/__tests__/unit/utils.test.js, app/client/api/asyncAPI.ts, app/client/components/AsyncModal.jsx, app/client/components/creditTransfer/CreditTransferList.tsx, app/client/components/pages/singleBulkDisbursementPage.jsx, app/client/components/transferAccount/TransferAccountList.tsx, app/client/genericState/actions.ts, app/client/genericState/index.ts, app/client/genericState/reducers.ts, app/client/genericState/sagas.ts, app/client/genericState/types.ts, app/client/reducers/async/actions.ts, app/client/reducers/async/reducers.ts, app/client/reducers/async/types.ts, app/client/reducers/metric/reducers.ts, app/client/reducers/metric/types.ts, app/client/reducers/rootReducer.ts, app/client/sagas/asyncSaga.ts, app/client/sagas/rootSaga.ts, app/client/utils.js, app/server/api/disbursement_api.py, app/server/models/disbursement.py, app/test_app/functional/api/test_bulk_disbursement_api.py
Draft of credit transfer list on bulk disbursement page  
**Todo**
=> List credit transfers on page
